# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'TestCocoaPodsIntegration' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CrowdConnectedCore', '1.7.0'
  pod 'CrowdConnectedShared', '1.7.0'
  pod 'CrowdConnectedIPS', '1.7.0'
  pod 'CrowdConnectedGeo', '1.7.0'
  pod 'CrowdConnectedCoreBluetooth', '1.7.0'
  pod 'AWSKinesis', '2.37.0'

end